// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CacheInvalidationFunction
 */
export interface CacheInvalidationFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/CacheInvalidation/CacheInvalidation.
 */
export class CacheInvalidationFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CacheInvalidationFunctionProps) {
    super(scope, id, {
      description: 'src/CacheInvalidation/CacheInvalidation.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/CacheInvalidation/CacheInvalidation.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}